In [109]:
data = [[0, 'weld', 0.9695907235145569, [31.935028076171875, 409.9541931152344, 228.4559326171875, 633.3704833984375]], 
 [1, '0_degree', 0.9683483242988586, [315.9129638671875, 92.39520263671875, 638.7367553710938, 370.0958251953125]], 
 [2, '30_degree', 0.956321120262146, [65.17212677001953, 26.556915283203125, 301.8634033203125, 427.2632751464844]], 
 [3, '90_degree', 0.9513142108917236, [4.2847900390625, 405.6118469238281, 301.99212646484375, 637.61962890625]], 
 [4, '90_degree', 0.8983685374259949, [303.06134033203125, 365.6444091796875, 637.703369140625, 636.5570068359375]], 
 [5, 'weld', 0.8419108986854553, [78.14288330078125, 222.38961791992188, 294.38836669921875, 277.7165222167969]], 
 [6, 'weld', 0.7610721588134766, [325.87091064453125, 219.21742248535156, 638.6672973632812, 253.00953674316406]], 
 [7, 'weld', 0.7564805746078491, [301.7332763671875, 595.0836181640625, 640.0, 618.0560302734375]]] 

In [89]:
import cv2
import numpy as np

In [125]:
def check_intersection(polygon1, polygon2):
    """
    Update to replace 
    """
    intersection = list()
    for point in polygon2:
        # print(point)
        result = cv2.pointPolygonTest(np.array(polygon1, dtype=np.float32), (float(point[0]), float(point[1])), measureDist=False)
        # if point inside return 1
        # if point outside return -1
        # if point on the contour return 0
        intersection.append(result)
    
    internal = 0
    external = 0

    for value in intersection:
        if value == -1:
            external += 1
        elif value == 1:
            internal += 1
        elif value == 0:
            internal += 1

    # print(internal)

    if internal >= 3:
        return True
    return False

def findContainingPairs(data):
    containing_pairs = list([])

    for label_item in data:
        idx, label, confidence, box = label_item
        if label in ['0_degree', '30_degree', '90_degree']:
            print(label)
            x1, y1, x2, y2 = box
            label_rect = (x1, y1, x2, y2)

            for weld_item in data:
                weld_idx, weld_label, weld_confidence, weld_box = weld_item
                if weld_label == 'weld':
                    weld_x1, weld_y1, weld_x2, weld_y2 = weld_box
                    weld_rect = (weld_x1, weld_y1, weld_x2, weld_y2)

                    object = list(label_rect)
                    weld = list(weld_rect)
                    object = np.array([[object[0] - 5, object[1]], [object[2]+5, object[1]], [object[2]+5, object[3] + 5], [object[0]-5, object[3] + 5]]).astype(int) #config because some case the coordinate weld higher object
                    weld = np.array([[weld[0], weld[1]], [weld[2], weld[1]], [weld[2], weld[3]], [weld[0], weld[3]]]).astype(int)
                    print(object)

                    if check_intersection(object, weld):
                        containing_pairs.append([weld_item, label_item])

    return containing_pairs

In [126]:
len(findContainingPairs(data))

0_degree
[[310  92]
 [643  92]
 [643 375]
 [310 375]]
[[310  92]
 [643  92]
 [643 375]
 [310 375]]
[[310  92]
 [643  92]
 [643 375]
 [310 375]]
[[310  92]
 [643  92]
 [643 375]
 [310 375]]
30_degree
[[ 60  26]
 [306  26]
 [306 432]
 [ 60 432]]
[[ 60  26]
 [306  26]
 [306 432]
 [ 60 432]]
[[ 60  26]
 [306  26]
 [306 432]
 [ 60 432]]
[[ 60  26]
 [306  26]
 [306 432]
 [ 60 432]]
90_degree
[[  0 405]
 [306 405]
 [306 642]
 [  0 642]]
[[  0 405]
 [306 405]
 [306 642]
 [  0 642]]
[[  0 405]
 [306 405]
 [306 642]
 [  0 642]]
[[  0 405]
 [306 405]
 [306 642]
 [  0 642]]
90_degree
[[298 365]
 [642 365]
 [642 641]
 [298 641]]
[[298 365]
 [642 365]
 [642 641]
 [298 641]]
[[298 365]
 [642 365]
 [642 641]
 [298 641]]
[[298 365]
 [642 365]
 [642 641]
 [298 641]]


4

In [ ]:
[[0, 'weld', 0.9695907235145569, [31.935028076171875, 409.9541931152344, 228.4559326171875, 633.3704833984375]], 
 [1, '0_degree', 0.9683483242988586, [315.9129638671875, 92.39520263671875, 638.7367553710938, 370.0958251953125]], 
 [2, '30_degree', 0.956321120262146, [65.17212677001953, 26.556915283203125, 301.8634033203125, 427.2632751464844]], 
 [3, '90_degree', 0.9513142108917236, [4.2847900390625, 405.6118469238281, 301.99212646484375, 637.61962890625]], 
 [4, '90_degree', 0.8983685374259949, [303.06134033203125, 365.6444091796875, 637.703369140625, 636.5570068359375]], 
 [5, 'weld', 0.8419108986854553, [78.14288330078125, 222.38961791992188, 294.38836669921875, 277.7165222167969]], 
 [6, 'weld', 0.7610721588134766, [325.87091064453125, 219.21742248535156, 638.6672973632812, 253.00953674316406]], 
 [7, 'weld', 0.7564805746078491, [301.7332763671875, 595.0836181640625, 640.0, 618.0560302734375]]]

In [ ]:
 [4, '90_degree', 0.8983685374259949, [303.06134033203125, 365.6444091796875, 637.703369140625, 636.5570068359375]], 
 [7, 'weld', 0.7564805746078491, [301.7332763671875, 595.0836181640625, 640.0, 618.0560302734375]]

In [ ]:
[[[6, 'weld', 0.7610721588134766, [325.87091064453125, 219.21742248535156, 638.6672973632812, 253.00953674316406]], 
  [1, '0_degree', 0.9683483242988586, [315.9129638671875, 92.39520263671875, 638.7367553710938, 370.0958251953125]]], 
  [[5, 'weld', 0.8419108986854553, [78.14288330078125, 222.38961791992188, 294.38836669921875, 277.7165222167969]], 
   [2, '30_degree', 0.956321120262146, [65.17212677001953, 26.556915283203125, 301.8634033203125, 427.2632751464844]]], 
   [[0, 'weld', 0.9695907235145569, [31.935028076171875, 409.9541931152344, 228.4559326171875, 633.3704833984375]], 
    [3, '90_degree', 0.9513142108917236, [4.2847900390625, 405.6118469238281, 301.99212646484375, 637.61962890625]]]]