In [2]:
import sys
sys.path.append(
    "D:\\Quan\\roboDK\\Vision-Machine-collab-Nhan\\VIKO_UltraRobot"
)
from config import config as CFG

In [2]:
pwd

'd:\\Quan\\roboDK\\Vision-Machine-collab-Nhan\\VIKO_UltraRobot\\src'

In [3]:
from ultralytics import YOLO
model = YOLO(CFG.MODEL['YOLOV9']['WEIGHT'])

In [4]:
import cv2
path_img = '../3weld.png'
img = cv2.imread(path_img, cv2.IMREAD_COLOR)
img_cvt = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img_resize = cv2.resize(img, (640, 640), interpolation= cv2.INTER_CUBIC)

dict_re = model.predict(img_resize)


0: 640x640 3 welds, 36.0ms
Speed: 3.0ms preprocess, 36.0ms inference, 1176.0ms postprocess per image at shape (1, 3, 640, 640)


In [5]:
dict_re

[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: ultralytics.engine.results.Masks object
 names: {0: 'weld', 1: 'other'}
 obb: None
 orig_img: array([[[145, 140, 122],
         [144, 140, 119],
         [143, 141, 122],
         ...,
         [137, 134, 122],
         [132, 133, 116],
         [152, 147, 128]],
 
        [[148, 145, 122],
         [143, 145, 119],
         [135, 144, 124],
         ...,
         [140, 138, 115],
         [135, 138, 113],
         [152, 146, 128]],
 
        [[146, 144, 124],
         [149, 143, 116],
         [145, 140, 115],
         ...,
         [133, 134, 113],
         [137, 135, 115],
         [149, 154, 132]],
 
        ...,
 
        [[149, 149, 114],
         [149, 144, 120],
         [148, 145, 128],
         ...,
         [184, 183, 161],
         [189, 182, 150],
         [208, 196, 172]],
 
        [[151, 140, 123],
         [142, 148, 126],
         [152

In [6]:
img_re = dict_re[0][0].orig_img

In [7]:
import numpy as np
def convert_mask(mask):
    color_image = np.zeros((640, 640, 3), dtype=np.uint8)
    color_image[:, :, 0] = mask[0]  
    color_image[:, :, 1] = mask[0]  
    color_image[:, :, 2] = mask[0]  
    return color_image

In [8]:
mask = dict_re[0].masks.data.detach().cpu().numpy()

In [14]:
mask_g = mask[0] + mask[1] + mask[2]

In [16]:
mask = cv2.normalize(mask_g, None, 255, 0, cv2.NORM_MINMAX, cv2.CV_8U)
mask = convert_mask(mask_g)

In [15]:
cv2.imshow('Output', mask_g)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
# display 1
import numpy as np
out = np.hstack([img_re, mask])

# Now show the image
cv2.imshow('Output', out)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [28]:
#display 2
coordinate_re = dict_re[0].masks.xy[0]

img_cp = img_re.copy()
pts = np.zeros((len(coordinate_re), 2))

for idx, point in enumerate(coordinate_re):
    cv2.circle(img_cp, (int(point[0]), int(point[1])), 1, (255, 0, 0), 1)
    pts[idx] = [int(point[0]), int(point[1])]
pts = np.array(pts, np.int32)

id = 0
cv2.fillPoly(img_cp, pts=[pts], color=(0, 0, 100 + int(id) * 100, 20))

array([[[175, 179, 152],
        [178, 179, 146],
        [179, 176, 152],
        ...,
        [185, 186, 157],
        [191, 183, 158],
        [195, 182, 156]],

       [[179, 178, 148],
        [182, 178, 146],
        [180, 178, 148],
        ...,
        [192, 182, 159],
        [195, 184, 154],
        [184, 186, 159]],

       [[180, 173, 148],
        [175, 178, 148],
        [184, 173, 149],
        ...,
        [189, 186, 159],
        [185, 188, 159],
        [193, 184, 158]],

       ...,

       [[171, 179, 149],
        [177, 176, 150],
        [184, 173, 148],
        ...,
        [213, 214, 181],
        [221, 210, 180],
        [223, 206, 180]],

       [[182, 175, 148],
        [174, 176, 152],
        [178, 177, 150],
        ...,
        [216, 214, 179],
        [219, 213, 184],
        [219, 214, 176]],

       [[177, 175, 150],
        [177, 178, 150],
        [182, 175, 150],
        ...,
        [218, 210, 181],
        [222, 209, 179],
        [217, 211, 182]]

In [29]:
cv2.imshow('Image', img_cp)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
coordinate_re[0]


array([        105,         176], dtype=float32)

In [31]:
coordinate_re[200]

array([        418,         510], dtype=float32)